app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', function () {return view('welcome');});
Route::get('/', 'IndexController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'auth.checkrole:admin', 'as' => 'admin.'], function () {
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'CategoriesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'CategoriesController@create']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CategoriesController@edit']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CategoriesController@destroy']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'CategoriesController@update']);
        Route::post('store', ['as' => 'store', 'uses' => 'CategoriesController@store']);
    });

    Route::group(['prefix' => 'clients', 'as' => 'clients.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ClientsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ClientsController@create']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ClientsController@edit']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'ClientsController@destroy']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'ClientsController@update']);
        Route::post('store', ['as' => 'store', 'uses' => 'ClientsController@store']);
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProductsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProductsController@create']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ProductsController@edit']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'ProductsController@destroy']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'ProductsController@update']);
        Route::post('store', ['as' => 'store', 'uses' => 'ProductsController@store']);
    });

    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'OrdersController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'OrdersController@create']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'OrdersController@edit']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'OrdersController@destroy']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'OrdersController@update']);
        Route::post('store', ['as' => 'store', 'uses' => 'OrdersController@store']);
    });

    Route::group(['prefix' => 'cupoms', 'as' => 'cupoms.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'CupomsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'CupomsController@create']);
        Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CupomsController@edit']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CupomsController@destroy']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'CupomsController@update']);
        Route::post('store', ['as' => 'store', 'uses' => 'CupomsController@store']);
    });
});

Route::group(['prefix' => 'customer', 'middleware' => 'auth.checkrole:client', 'as' => 'customer.'], function () {
    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'CheckoutController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'CheckoutController@create']);
        Route::post('store', ['as' => 'store', 'uses' => 'CheckoutController@store']);
    });
});

Route::post('oauth/access_token', function () {
    return Response::json(Authorizer::issueAccessToken());
});

Route::group(['prefix' => 'api', 'middleware' => 'oauth', 'as' => 'api.'], function () {

    Route::group(['prefix' => 'client', 'middleware' => 'oauth.checkrole:client', 'as' => 'client.'], function () {
        Route::resource('order',
            'Api\Client\ClientCheckoutController',
            ['except' => ['edit', 'create', 'destroy']
            ]);
    });

    Route::group(['prefix' => 'deliveryman', 'middleware' => 'oauth.checkrole:deliveryman', 'as' => 'deliveryman . '], function () {
        Route::resource('order',
            'Api\Deliveryman\DeliverymanCheckoutController',
            ['except' => ['edit', 'create', 'destroy', 'store']
            ]);
        Route::patch('order/{id}/update-status', [
            'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
            'as' => 'orders.update-status'
        ]);
    });

});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status',
        'cupom_id'
    ];

    public function transform()
    {
        return [
            'order' => $this->id,
            'order_items' => $this->items,
        ];
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

    public function product()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/OrdersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Binho
 * Date: 31/10/2015
 * Time: 10:27
 */

namespace CodeDelivery\Http\Controllers;


use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

class OrdersController extends Controller
{
    /**
     * @var OrderRepository
     */
    private $repository;

    public function __construct(OrderRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $orders = $this->repository->paginate(5);
        return view('admin.orders.index', compact('orders'));
    }

    public function edit($id, UserRepository $userRepository)
    {
        $list_status = [0=>'Pendente', 1=>'A Caminho', 2=>'Entregue', 3=>'Cancelado'];
        $order = $this->repository->find($id);
        $deliveryman = $userRepository->getDeliverymen();

        return view('admin.orders.edit', compact('order', 'deliveryman', 'list_status'));
    }

    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->repository->update($all, $id);

        return redirect()->route('admin.orders.index');
    }

}

resources/views/customer/order/create.blade.php
@extends('app')

@section('content')

    <div class="container">
        <h3>Novo pedido</h3>


        @include('errors._check')

        {!! Form::open(['route' => 'customer.order.store', 'class' => 'form']) !!}
        <div class="form-group">
            <label for="">Total: <b id="total"></b></label>
            <br>
            <a href="#" id="btnNewItem" class="btn btn-default">Novo Item</a>
            <br><br>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <select name="items[0][product_id]" class="form-control">
                            @foreach($products as $p)
                                <option value="{{$p->id}}" data-price="{{$p->price}}">{{$p->name}} -- {{$p->price}}</option>
                            @endforeach
                        </select>
                    </td>
                    <td>
                        {!! Form::text('items[0][qtd]', 1, ['class' => 'form-control']) !!}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="form-group">
            {!! Form::submit('Criar pedido', ['class' => 'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>

@endsection

@section('post-script')
    <script>
        $('#btnNewItem').click(function () {
            var row = $('table tbody > tr:last'),
                    newRow = row.clone(),
                    length = $('table tbody tr').length;

            newRow.find('td').each(function() {
                var td = $(this),
                        input = td.find('input, select'),
                        name = input.attr('name');
                input.attr('name', name.replace((length - 1) + '', length + ''));
            });

            newRow.find('input').val(1);
            newRow.insertAfter(row);
            calculateTotal();
        });

        $(document.body).on('click', 'select', function(){
           calculateTotal()
        });

        $(document.body).on('blur', 'input', function(){
           calculateTotal();
        });

        function calculateTotal(){
            var total = 0,
                    trLen = $('table tbody tr').length,
                    tr = null, price, qtd;

            for (var i=0; i<trLen; i++){
                tr = $('table tbody tr').eq(i);
                price = tr.find(':selected').data('price');
                qtd = tr.find('input').val();
                total += price * qtd;
            }
            $('#total').html(total);
        }
    </script>

@endsection

resources/views/customer/order/index.blade.php
@extends('app')

@section('content')

    <div class="container">
        <h3>Meus pedidos</h3>

        @include('errors._check')

        <a href="{{route('customer.order.create')}}" class="btn btn-default">Novo pedido</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th width="7%">ID</th>
                <th>Total</th>
                <th width="15%">Status</th>
            </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <?php
                if($order->status == 0) : $class = 'warning';
                elseif($order->status == 1): $class = 'info';
                elseif($order->status == 2): $class = 'success';
                elseif($order->status == 3): $class = 'danger';
                else: $class = 'active';
                endif;
                ?>
            <tr class="<?= $class ?>">
                <td>{{$order->id}}</td>
                <td>{{$order->total}}</td>
                <td>
                    @if($order->status == 0)
                        Pendente
                    @elseif($order->status == 1)
                        A Caminho
                    @elseif($order->status == 2)
                        Entregue
                    @elseif($order->status == 3)
                        Cancelado
                    @endif
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

    {!! $orders->render() !!}

@endsection